maintainer       "Lisa Walley"
maintainer_email "lwalley@mbl.edu"
license          "Apache 2.0"
description      "Installs/Configures DSpace"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"
depends          "apt"
depends          "database"
depends          "java"
depends          "ant"
depends          "maven"
depends          "tomcat"
